name: CV build

on: [push]

jobs:
  build_cv:
    runs-on: ubuntu-latest
    name: build CV
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: run actiom.yml
          uses: ./
          
        - name: Commit changes
          run: |
            git config --local user.email "nikitartamonov2112@gmail.com"
            git config --local user.name "Nikita Artamonov"
            git add --all
            git commit -m "Update CV"
            git push origin HEAD:github-pages-deployment
            git push origin HEAD:main
            mkdir to_pages
            mv ${{ github.workspace }}/CV/resume.pdf ${{ github.workspace }}/to_pages/resume.pdf
            mv ${{ github.workspace }}/CV/index.html ${{ github.workspace}}/to_pages/index.html
            
        - name: Deploy CV
          if: success()
          uses: crazy-max/ghaction-github-pages@v3
          with:
            target_branch: github-pages-deployment
            build_dir: to_pages
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
          
